from tkinter import *
root=Tk()
h,w=root.winfo_screenheight(),root.winfo_screenwidth()
root.geometry('%dx%d+0+0'%(w,h))
bus=PhotoImage(file='C:\\Users\\hp\\Downloads\\Bus.png')
Label(root,image=bus).grid(row=0,column=0,columnspan=12,padx=w/2.5)
Label(root,text='Online Bus Booking System',font='Arial 20',fg='Red',bg='Sky Blue').grid(row=1,column=0,columnspan=12)
Label(root,text='Add Bus Route Details',font='Arial 18',fg='Green',bg='Sky Blue').grid(row=2,columnspan=12,pady=20)
Label(root,text='Route ID',font='Arial 10').grid(row=3,column=2)
Entry(root).grid(row=3,column=3)
Label(root,text='Station Name',font='Arial 10').grid(row=3,column=4)
Entry(root).grid(row=3,column=5)
Label(root,text='Station ID',font='Arial 10').grid(row=3,column=6)
Entry(root).grid(row=3,column=7)
Button(root,text='Add Route',font='Arial 10',bg='Pale Green').grid(row=3,column=8)
Button(root,text='Delete Route',font='Arial 10',fg='Red').grid(row=3,column=9)
home=PhotoImage(file='C:\\Users\\hp\\Documents\\AP PROJECT\\home.png')
Button(root,image=home,font='Arial 10',bg='Pale Green').grid(row=4,column=8,pady=50)

root.mainloop()
